# Generated by Django 3.1.5 on 2021-01-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('photo_url', models.URLField()),
                ('trailer_url', models.URLField()),
                ('release_date', models.DateField()),
                ('duration', models.TimeField()),
                ('directors', models.TextField()),
                ('cast', models.TextField()),
                ('description', models.TextField(max_length=1000)),
                ('genres', models.ManyToManyField(to='moviedb.Genre')),
            ],
        ),
    ]
