# Generated by Django 3.1.5 on 2021-01-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.DurationField(),
        ),
    ]
